[2024-07-21 03:41:05,433] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: ETL_task.load_from_mysql 2021-07-28T00:00:00+00:00 [queued]>
[2024-07-21 03:41:05,497] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: ETL_task.load_from_mysql 2021-07-28T00:00:00+00:00 [queued]>
[2024-07-21 03:41:05,497] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-07-21 03:41:05,499] {taskinstance.py:1088} INFO - Starting attempt 2 of 2
[2024-07-21 03:41:05,502] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-07-21 03:41:05,550] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): load_from_mysql> on 2021-07-28T00:00:00+00:00
[2024-07-21 03:41:05,608] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ETL_task', 'load_from_mysql', '2021-07-28T00:00:00+00:00', '--job-id', '158', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ELT.py', '--cfg-path', '/tmp/tmpcn8nmcus', '--error-file', '/tmp/tmpigbboodg']
[2024-07-21 03:41:05,610] {standard_task_runner.py:77} INFO - Job 158: Subtask load_from_mysql
[2024-07-21 03:41:05,589] {standard_task_runner.py:52} INFO - Started process 187 to run task
[2024-07-21 03:41:51,284] {local_task_job.py:194} WARNING - Recorded pid 275 does not match the current pid 187
[2024-07-21 03:41:51,298] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 187
[2024-07-21 03:41:51,397] {process_utils.py:66} INFO - Process psutil.Process(pid=187, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='03:41:05') (187) terminated with exit code Negsignal.SIGTERM
