[2024-07-21 03:41:05,441] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: ETL_task.load_from_mysql 2021-07-17T00:00:00+00:00 [queued]>
[2024-07-21 03:41:05,506] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: ETL_task.load_from_mysql 2021-07-17T00:00:00+00:00 [queued]>
[2024-07-21 03:41:05,507] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-07-21 03:41:05,508] {taskinstance.py:1088} INFO - Starting attempt 2 of 2
[2024-07-21 03:41:05,509] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-07-21 03:41:05,558] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): load_from_mysql> on 2021-07-17T00:00:00+00:00
[2024-07-21 03:41:05,572] {standard_task_runner.py:52} INFO - Started process 186 to run task
[2024-07-21 03:41:05,614] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ETL_task', 'load_from_mysql', '2021-07-17T00:00:00+00:00', '--job-id', '157', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ELT.py', '--cfg-path', '/tmp/tmpcspgk301', '--error-file', '/tmp/tmpmvfpbvrb']
[2024-07-21 03:41:05,614] {standard_task_runner.py:77} INFO - Job 157: Subtask load_from_mysql
[2024-07-21 03:41:51,255] {local_task_job.py:194} WARNING - Recorded pid 220 does not match the current pid 186
