[2024-07-21 03:41:05,414] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: ETL_task.load_from_mysql 2024-07-21T03:35:10.131937+00:00 [queued]>
[2024-07-21 03:41:05,472] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: ETL_task.load_from_mysql 2024-07-21T03:35:10.131937+00:00 [queued]>
[2024-07-21 03:41:05,474] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-07-21 03:41:05,484] {taskinstance.py:1088} INFO - Starting attempt 2 of 2
[2024-07-21 03:41:05,485] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-07-21 03:41:05,554] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): load_from_mysql> on 2024-07-21T03:35:10.131937+00:00
[2024-07-21 03:41:05,571] {standard_task_runner.py:52} INFO - Started process 185 to run task
[2024-07-21 03:41:05,620] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ETL_task', 'load_from_mysql', '2024-07-21T03:35:10.131937+00:00', '--job-id', '162', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ELT.py', '--cfg-path', '/tmp/tmp1uhfk6yh', '--error-file', '/tmp/tmpzravzplz']
[2024-07-21 03:41:05,622] {standard_task_runner.py:77} INFO - Job 162: Subtask load_from_mysql
[2024-07-21 03:41:51,244] {local_task_job.py:194} WARNING - Recorded pid 219 does not match the current pid 185
[2024-07-21 03:41:51,284] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 185
[2024-07-21 03:41:51,352] {process_utils.py:66} INFO - Process psutil.Process(pid=185, status='terminated', exitcode=<Negsignal.SIGTERM: -15>, started='03:41:05') (185) terminated with exit code Negsignal.SIGTERM
